### ISSUE TITLE
Package versions?

### ISSUE THREAD

**Issue by ChenyuL** [abchapman93/ReHouSED#1]
Hi team, 
Thanks for providing this tool! I'm trying to download it and run some examples, but had some errors. 
I downloaded the code and used 

> python setup.py install

for example 

> "from helpers import ENT_COLORS"  No module name 'helpers' 

> [E997] Tokenizer special cases are not allowed to modify the text. This would map 'z59.0' to 'Z59.0' given token attributes '[{65: 'Z59.0'}]'.

Could you please provide the package/dependicies version and instructions on how to solve the issue?

Thank you!

**Comment by abchapman93** [comment]
Hi!
Sorry for the late reply on this. Thanks for bringing up this issue, the issue is that the medspacy version specified in setup.py allows too high of a version - this hasn't been updated for spaCy 3 and should use spacy 2. I'll update the package, but in the mean time if you manually install these versions it should fix the issue:

spacy==2.3.2
medspacy==0.1.0.2
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz 

Let me know if that doesn't solve the issue!
